### ISSUE TITLE
"jack" option does not appear at alvr dashboard

### ISSUE THREAD

**Issue by LuNeder** [20PercentRendered/ALVR-audio#1]
OpenSUSE does not have the pipewire-jack package, but does have pipewire-libjack that should be the same thing

However, the "jack" option does not appear at alvr dashboard. Choosing anything else either gives me errors or just no sound at all

**Comment by LuNeder** [comment]
It works now
Still no jack option, but choosing "pipewire" instead and then using Helvum to manually reroute audio to "pipewire alsa" makes it work

Still: I have to manually reroute the audio for every single app I open, every single time I open. So maybe this could be a new title for this issue: I have to manually reroute apps every time in order to hear them.

**Comment by Rosentti** [comment]
Sorry for the late response, didn't get a notification. Does Helvum have a patchbay like QJackCtl? If so, you can save the route. Also, are you running steam from flatpak? It may cause issues.

**Comment by Rosentti** [comment]
No response, and cannot reproduce.

**Comment by LuNeder** [comment]
> Sorry for the late response, didn't get a notification. Does Helvum have a patchbay like QJackCtl? If so, you can save the route. Also, are you running steam from flatpak? It may cause issues.

Sorry for the late response, I did get a notification but I forgot to reply

Nope, not on flatpak

Using Jack to save the route on patchbay works when selecting the specific app on the output and routing it to the "vrserver\/PipeWire\ ALSA\[vrserver\] 1" input, but I have to do so manually every time I open a program that I haven’t opened and routed before (now using Jack instead of Helvum, so it stays saved if I open the same program on another day). This way I only have to manually route a program the first time I use that program on VR, not every time I open it.

However, both the “VirtMain monitor” output and the “alvrin” input ends up unused this way so I’m not sure if the script actually has to be enabled in order to use this workaround.

Routing the VirtMain monitor to the previously mentioned vrserver/PipeWire input gives only a very high intermittent noise.

**Comment by Rosentti** [comment]
I actually had this issue myself when I dusted off my VR setup but I decided to just use headphones on top of my headset. I tried to switch audio devices around to no avail. Maybe an ALVR or SteamVR update broke it. The connections connected in QJackCtl but no sound came out of the VR glasses. Could be broken on ALVR's side.
